Install Tower
redhat-cop/aap_configuration_template pull request #4
Opened 2020-07-29 11:32 UTC by Tompage1994

Adds ability to install Tower.

I think the roles should probably end up inside of a collection. perhaps something like `redhat_cop.tower_utils` (so a new repo required)?

I'm not sure there will be a good way to run automated tests of this.

Do we think this repo should contain things like this or should it perhaps live elsewhere?

2020-07-30 14:51 UTC, aoyawale approved these changes
everything looks to me. Yes, we should make it into a collection but this is a good starting point.

2020-07-31 14:54 UTC, sean-m-sullivan commented on ansible.cfg
> +collections_paths=colelctions
Typo here on word collections.

2020-07-31 14:58 UTC, sean-m-sullivan requested changes
Looks good, just have that one minor typo, I like how you did the 3.6 vs 3.7 rabbitmq changes as well.

2020-07-31 14:59 UTC, Tompage1994 commented on ansible.cfg
> +collections_paths=colelctions
Fixed

2020-07-31 21:24 UTC, sean-m-sullivan approved these changes
Looks Good!

2020-08-03 18:46 UTC, merged